openapi: 3.0.1
info:
  title: Naver Keyword Research API
  description: 네이버 키워드 검색량을 조회하는 API입니다.
  version: "1.0.0"

servers:
  - url: https://server-production-a05c.up.railway.app  # 👈 이 줄 반드시 포함되어야 함

paths:
  /doNaverKeywordResearch:
    post:
      summary: 키워드 검색량 조회
      operationId: doNaverKeywordResearch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/KeywordRequest"
      responses:
        '200':
          description: 성공적으로 키워드 검색량을 반환함
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/KeywordData"

components:
  schemas:
    KeywordRequest:
      type: object
      properties:
        keyword:
          type: string
    KeywordData:
      type: object
      properties:
        keyword:
          type: string
        search_volume_pc:
          type: integer
        search_volume_mobile:
          type: integer
        competition:
          type: string
